    pipeline {
    agent any
    environment {
        ARTIFACTORY_ACCESS_TOKEN = credentials('JFrog-Access-Token')
    }
    tools {
        maven 'maven'
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Uplpoad artifact to jfrog') {
            steps {
                sh 'jf rt upload --url https://jfrog71.jfrog.io/artifactory/ --access-token ${ARTIFACTORY_ACCESS_TOKEN} ./*.jar java-web-app/'
            }
        }
    }
}
